// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SessionRequestCommand.proto

#ifndef PROTOBUF_SessionRequestCommand_2eproto__INCLUDED
#define PROTOBUF_SessionRequestCommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif



#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace UIH {
namespace XR {
namespace Basis {
namespace Proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SessionRequestCommand_2eproto();
void protobuf_AssignDesc_SessionRequestCommand_2eproto();
void protobuf_ShutdownFile_SessionRequestCommand_2eproto();

class SessionRequestCommand;

// ===================================================================

class SessionRequestCommand : public ::google::protobuf::Message {
 public:
  SessionRequestCommand();
  virtual ~SessionRequestCommand();
  
  SessionRequestCommand(const SessionRequestCommand& from);
  
  inline SessionRequestCommand& operator=(const SessionRequestCommand& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SessionRequestCommand& default_instance();
  
  void Swap(SessionRequestCommand* other);
  
  // implements Message ----------------------------------------------
  
  SessionRequestCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SessionRequestCommand& from);
  void MergeFrom(const SessionRequestCommand& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 CommandId = 1;
  inline bool has_commandid() const;
  inline void clear_commandid();
  static const int kCommandIdFieldNumber = 1;
  inline ::google::protobuf::int32 commandid() const;
  inline void set_commandid(::google::protobuf::int32 value);
  
  // repeated string Parameters = 2;
  inline int parameters_size() const;
  inline void clear_parameters();
  static const int kParametersFieldNumber = 2;
  inline const ::std::string& parameters(int index) const;
  inline ::std::string* mutable_parameters(int index);
  inline void set_parameters(int index, const ::std::string& value);
  inline void set_parameters(int index, const char* value);
  inline void set_parameters(int index, const char* value, size_t size);
  inline ::std::string* add_parameters();
  inline void add_parameters(const ::std::string& value);
  inline void add_parameters(const char* value);
  inline void add_parameters(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& parameters() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_parameters();
  
  // @@protoc_insertion_point(class_scope:UIH.XR.Basis.Proto.SessionRequestCommand)
 private:
  inline void set_has_commandid();
  inline void clear_has_commandid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> parameters_;
  ::google::protobuf::int32 commandid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_SessionRequestCommand_2eproto();
  friend void protobuf_AssignDesc_SessionRequestCommand_2eproto();
  friend void protobuf_ShutdownFile_SessionRequestCommand_2eproto();
  
  void InitAsDefaultInstance();
  static SessionRequestCommand* default_instance_;
};
// ===================================================================


// ===================================================================

// SessionRequestCommand

// required int32 CommandId = 1;
inline bool SessionRequestCommand::has_commandid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SessionRequestCommand::set_has_commandid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SessionRequestCommand::clear_has_commandid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SessionRequestCommand::clear_commandid() {
  commandid_ = 0;
  clear_has_commandid();
}
inline ::google::protobuf::int32 SessionRequestCommand::commandid() const {
  return commandid_;
}
inline void SessionRequestCommand::set_commandid(::google::protobuf::int32 value) {
  set_has_commandid();
  commandid_ = value;
}

// repeated string Parameters = 2;
inline int SessionRequestCommand::parameters_size() const {
  return parameters_.size();
}
inline void SessionRequestCommand::clear_parameters() {
  parameters_.Clear();
}
inline const ::std::string& SessionRequestCommand::parameters(int index) const {
  return parameters_.Get(index);
}
inline ::std::string* SessionRequestCommand::mutable_parameters(int index) {
  return parameters_.Mutable(index);
}
inline void SessionRequestCommand::set_parameters(int index, const ::std::string& value) {
  parameters_.Mutable(index)->assign(value);
}
inline void SessionRequestCommand::set_parameters(int index, const char* value) {
  parameters_.Mutable(index)->assign(value);
}
inline void SessionRequestCommand::set_parameters(int index, const char* value, size_t size) {
  parameters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SessionRequestCommand::add_parameters() {
  return parameters_.Add();
}
inline void SessionRequestCommand::add_parameters(const ::std::string& value) {
  parameters_.Add()->assign(value);
}
inline void SessionRequestCommand::add_parameters(const char* value) {
  parameters_.Add()->assign(value);
}
inline void SessionRequestCommand::add_parameters(const char* value, size_t size) {
  parameters_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SessionRequestCommand::parameters() const {
  return parameters_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SessionRequestCommand::mutable_parameters() {
  return &parameters_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Basis
}  // namespace XR
}  // namespace UIH

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SessionRequestCommand_2eproto__INCLUDED
