// Generated by the protocol buffer compiler.  DO NOT EDIT!
#include "stdafx.h"
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SessionRequestCommand.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace UIH {
namespace XR {
namespace Basis {
namespace Proto {

namespace {

const ::google::protobuf::Descriptor* SessionRequestCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SessionRequestCommand_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SessionRequestCommand_2eproto() {
  protobuf_AddDesc_SessionRequestCommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SessionRequestCommand.proto");
  GOOGLE_CHECK(file != NULL);
  SessionRequestCommand_descriptor_ = file->message_type(0);
  static const int SessionRequestCommand_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionRequestCommand, commandid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionRequestCommand, parameters_),
  };
  SessionRequestCommand_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SessionRequestCommand_descriptor_,
      SessionRequestCommand::default_instance_,
      SessionRequestCommand_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionRequestCommand, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionRequestCommand, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SessionRequestCommand));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SessionRequestCommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SessionRequestCommand_descriptor_, &SessionRequestCommand::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SessionRequestCommand_2eproto() {
  delete SessionRequestCommand::default_instance_;
  delete SessionRequestCommand_reflection_;
}

void protobuf_AddDesc_SessionRequestCommand_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033SessionRequestCommand.proto\022\022UIH.XR.Ba"
    "sis.Proto\">\n\025SessionRequestCommand\022\021\n\tCo"
    "mmandId\030\001 \002(\005\022\022\n\nParameters\030\002 \003(\014", 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SessionRequestCommand.proto", &protobuf_RegisterTypes);
  SessionRequestCommand::default_instance_ = new SessionRequestCommand();
  SessionRequestCommand::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SessionRequestCommand_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SessionRequestCommand_2eproto {
  StaticDescriptorInitializer_SessionRequestCommand_2eproto() {
    protobuf_AddDesc_SessionRequestCommand_2eproto();
  }
} static_descriptor_initializer_SessionRequestCommand_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SessionRequestCommand::kCommandIdFieldNumber;
const int SessionRequestCommand::kParametersFieldNumber;
#endif  // !_MSC_VER

SessionRequestCommand::SessionRequestCommand()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SessionRequestCommand::InitAsDefaultInstance() {
}

SessionRequestCommand::SessionRequestCommand(const SessionRequestCommand& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SessionRequestCommand::SharedCtor() {
  _cached_size_ = 0;
  commandid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SessionRequestCommand::~SessionRequestCommand() {
  SharedDtor();
}

void SessionRequestCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SessionRequestCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SessionRequestCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SessionRequestCommand_descriptor_;
}

const SessionRequestCommand& SessionRequestCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SessionRequestCommand_2eproto();  return *default_instance_;
}

SessionRequestCommand* SessionRequestCommand::default_instance_ = NULL;

SessionRequestCommand* SessionRequestCommand::New() const {
  return new SessionRequestCommand;
}

void SessionRequestCommand::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    commandid_ = 0;
  }
  parameters_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SessionRequestCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 CommandId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &commandid_)));
          set_has_commandid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_Parameters;
        break;
      }
      
      // repeated bytes Parameters = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Parameters:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_parameters()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_Parameters;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SessionRequestCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 CommandId = 1;
  if (has_commandid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->commandid(), output);
  }
  
  // repeated bytes Parameters = 2;
  for (int i = 0; i < this->parameters_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->parameters(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SessionRequestCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 CommandId = 1;
  if (has_commandid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->commandid(), target);
  }
  
  // repeated bytes Parameters = 2;
  for (int i = 0; i < this->parameters_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->parameters(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SessionRequestCommand::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 CommandId = 1;
    if (has_commandid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->commandid());
    }
    
  }
  // repeated bytes Parameters = 2;
  total_size += 1 * this->parameters_size();
  for (int i = 0; i < this->parameters_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->parameters(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SessionRequestCommand::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SessionRequestCommand* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SessionRequestCommand*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SessionRequestCommand::MergeFrom(const SessionRequestCommand& from) {
  GOOGLE_CHECK_NE(&from, this);
  parameters_.MergeFrom(from.parameters_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_commandid()) {
      set_commandid(from.commandid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SessionRequestCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SessionRequestCommand::CopyFrom(const SessionRequestCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SessionRequestCommand::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void SessionRequestCommand::Swap(SessionRequestCommand* other) {
  if (other != this) {
    std::swap(commandid_, other->commandid_);
    parameters_.Swap(&other->parameters_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SessionRequestCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SessionRequestCommand_descriptor_;
  metadata.reflection = SessionRequestCommand_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Basis
}  // namespace XR
}  // namespace UIH

// @@protoc_insertion_point(global_scope)
