#define XR_SESSION_MANAGER_SOURCE_NAME "SessiongManager"
#define LOG_INFO(Info) \
     LOG_DEV_INFO_2(XR_SESSION_MANAGER_SOURCE_NAME, 0) << Info;
#define LOG_WARNING(Info) \
     LOG_DEV_WARNING_2(XR_SESSION_MANAGER_SOURCE_NAME, 0) << Info;
#define LOG_ERROR(Info) \
    LOG_DEV_ERROR_2(XR_SESSION_MANAGER_SOURCE_NAME, 0) << Info;